# Generated by Django 2.0 on 2017-12-19 21:49

import cameras.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('insertDate', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bios', models.TextField()),
                ('contact', models.CharField(help_text='Contact Name for this Collection, *information is Public', max_length=50)),
                ('number', models.CharField(blank=True, help_text='Conact Number *not public', max_length=18, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='*only public if you wish, by selecting checkbox bellow.', max_length=40, null=True, verbose_name='Email Address ')),
                ('emailpublic', models.BooleanField(default=0, help_text='Selecting this option will display your Email Address on the public web pages.', verbose_name='Make my Email Address visible')),
                ('city', models.CharField(max_length=35)),
                ('url', models.URLField(blank=True, help_text='If you have a webpage you would like guest to viste, please supply here.', max_length=100, null=True)),
                ('insertDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bios', models.TextField(blank=True)),
                ('insertDate', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('url', models.URLField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('modelNumber', models.CharField(max_length=20, verbose_name='Model Number')),
                ('releasedDate', models.DateField(verbose_name='Product Release Date')),
                ('photo', models.FileField(max_length=30, upload_to=cameras.helper.RenameUploadedFileName('cameras'))),
                ('insertDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Brand')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=300)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Company'),
        ),
    ]
