# Generated by Django 2.0 on 2017-12-19 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20171219_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='bios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='releasedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Product Release Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
